# main.py - project "front door"
from fastapi import FastAPI # Core web framework
import logging # Std-lib audit trail

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-8s %(message)s"
)
# Defense auditors insist on ISO timestamps and level tags.

# Create ASGI application object

app = FastAPI(
    title="EVA Sentinel",
    version="0.1.0",
    description="Real-time no-fly-zone monitor (scaffold :)"
)
# Three strings land on the OpenAPI page that is autogenerated.

# Liveness Probe
@app.get("/ping", summary="Health probe")
def ping() -> dict[str, str]:
    """Simple heartbeat used by CI and Kubernetes readiness checks."""
    return {"status": "alive"}


